### ISSUE TITLE
[BACK] Service API

### ISSUE THREAD

**Issue by bricedumontepita** [mithy45/angular_project#2]
- Créer un service qui permet d'appeler l'API, avec toutes les fonctions utiles pour récupérer les données

**Comment by mithy45** [comment]
> dans Last.fm : artist.getInfo je veux le nom, et tags.tag.name (le style de musique) avoir une liste de tag avec une recherche (pas trouvé)

Tu peux utiliser la fonction "getListArtistBySearch(searchName: string)" du service LastFmApiService : Ca va te return un object de type Observable<any> et tu devras utiliser la fonction subscrible de l'object retourné exemple :

getListArtistBySearch("dems").subscribe(data => {
console.log(data); // qui est la réponse JSON
})
